# 全局配置

# 项目相关配置
linkai:
  # 名称
  name: linkai
  # 版本
  version: 0.0.1
  # 版权年份
  copyrightYear: 2020
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/linkai/uploadPath
  # 获取ip地址开关
  addressEnabled: false
# database config
spring:
  profiles:
    active: dev
  # freemarker config
  freemarker:
    charset: utf-8
    suffix: .html
  # staticResource
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${linkai.profile}
  # upload file config
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    content-type: text/html
    mode: HTML5
    cache: false
#  数据库如果时间相差8小时：可以将字段类型设置timestamp，或者使用这种
# jackson:
#    default-property-inclusion: non_null
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GTM+8

uploadPath: C:/upload/
# 配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
  mapper-locations: classpath*:/mapper/**/*.xml

# pageHelper config
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# print sql level
logging:
  level:
    com.cxff: debug



